### PR TITLE
Creating connection to Prismic. Creating Blog component. Fetching posts from Prismic

### PR DESCRIPTION
**Pull request by manuelalferez**
Please @pmascaraque don't merge yet, the pull request has not yet been completed. For now, we have a `/blog` page where we fetch our posts 🚀 🥳

Preview:
Captura de pantalla 2021-11-06 a las 23 07 19

Posts in Prismic:
Captura de pantalla 2021-11-06 a las 23 10 01

For now, on the `/blog` page we are bringing the **title**, **date of publication** and **summary** of each post. .

Captura de pantalla 2021-11-06 a las 23 11 00

The date of publication doesn't have to be entered by the "news creator", it is created automatically. Here you can see the JSON object from which we fetch:
Captura de pantalla 2021-11-06 a las 23 13 33

### CODE REVIEW

**Comment by manuelalferez** [comment]
News section have been created. One thing less 🥳
Captura de pantalla 2021-11-19 a las 9 17 13

**Comment by manuelalferez** [comment]
This pull request is ready to be merged

**Comment by manuelalferez** [comment]
Captura de pantalla 2021-11-19 a las 13 26 16

**Comment by manuelalferez** [comment]
Could you fix the conflicts? Also, if you could fix the bugs in the server to at least get the new features to production. If they don't pass the vercel tests, we can't see anything.

**Review by pmascaraque — APPROVED** [review]

**Pull request merged**
